version: 2.1

orbs:
  win: circleci/windows@5.0.0

commands:
  fetch_merge_ref:
    description: "Fetch the merge ref for a pull request"
    steps:
      - run:
          name: Fetch merge ref
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              git fetch origin refs/pull/$CIRCLE_PR_NUMBER/merge
              git checkout FETCH_HEAD
            fi

jobs:
  build_doc_r:
    machine:
      image: default

    steps:
      - checkout
      - fetch_merge_ref
      - run:
          name: Build documentation
          working_directory: docs/api_reference
          command: |
            ./build-rdoc.sh
            if [ -n "$(git status --porcelain)" ]; then
              exit 1
            fi

  # TODO: Add a job to build the python and java api reference
  build_doc:
    docker:
      - image: cimg/node:20.17

    steps:
      - checkout
      - fetch_merge_ref
      - run:
          name: Build documentation
          working_directory: docs
          command: |
            yarn build
      - run:
          name: Check for broken links
          working_directory: docs
          command: |
            python broken_links.py
      - run:
          name: Test examples
          working_directory: docs
          command: |
            make test-examples
      - store_artifacts:
          path: docs/build/

  mlflow-recipes:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - fetch_merge_ref
      - run:
          name: Pull submodule
          command: |
            git submodule update --init --recursive
      - run:
          name: Install dependencies
          command: |
            pip install .
            pip install nbconvert ipykernel
      - run:
          name: Run CLI
          working_directory: examples/recipes/regression
          environment:
            MLFLOW_RECIPES_PROFILE: local
          command: |
            mlflow recipes run
      - run:
          name: Run notebook
          working_directory: examples/recipes/regression
          environment:
            MLFLOW_RECIPES_PROFILE: local
          command: |
            jupyter nbconvert --to html --execute notebooks/jupyter.ipynb
            jupyter nbconvert --to html --execute notebooks/jupyter.ipynb --output dark-jupyter --HTMLExporter.theme=dark

      - store_artifacts:
          path: ~/.mlflow/recipes
      - store_artifacts:
          path: examples/recipes/regression/notebooks/jupyter.html
      - store_artifacts:
          path: examples/recipes/regression/notebooks/dark-jupyter.html

  # A job to get a free Windows VM for testing. See https://circleci.com/docs/ssh-access-jobs/ for how to set up SSH access.
  windows:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout

workflows:
  build:
    jobs:
      - build_doc
      - build_doc_r
      - mlflow-recipes
      - windows
